### PR TITLE
[WIP] Can `init!` and `close!` a devlist globally.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
This is so that I can use CUDArt in the following way:

```julia
CUDArt.init!(devlist)
# Do CUDA work
CUDArt.close!(devlist)
```

instead of

```julia
CUDArt.devices(...) do
   # Do CUDA work
end
```

which is not well-suited for libraries AFAICT. (Note that the `CUDArt.devices(...)` way still works, this just makes the former possible.)

This changes `mdutils` to be a global in the same way as `ptxdict` and also cleans-up `ptxdict` entries upon `close!`, for which I had to slightly change the type of `ptxdict`.

`Pkg.test("CUDArt")` works for me, although it once randomly failed [this one](https://github.com/JuliaGPU/CUDArt.jl/blob/master/test/gc.jl#L57). I wasn't able to reproduce the failure, so I can't know whether it happened because of these changes or not.

If you are OK with these changes, I'll add some tests and documentation. I'm also unsure whether `init!` and `close!` should be renamed to `init` and `close`, since they don't modify their arguments, but they do change global (library) state.

### CODE REVIEW

**Comment by timholy** [comment]
You can do it this way:
```jl
cumodules = [CuModule() for dev in devlist]
CUDArt.init!(cumodules, devlist)
# Do CUDA work
CUDArt.close!(cumodules, devlist)
```
That doesn't require a global. Not that I think the global is a horrible idea, mind you. But neither is the above so different that I think this PR is obviously an improvement.

However, I'm looking over this code and will see if I see other opportunities to make it simpler. If you see them yourself, by all means point them out.

**Comment by lucasb-eyer** [comment]
Fair point. The way you show doesn't clear `ptxdict` upon `close!`, so I could remove the global `mdutils` from this PR and only keep the `ptxdict` cleanup if you prefer.

It just seem weird to me that the user must handle `cumodules`, but `ptxdict` is handled by the library, even though AFAICT they go hand in hand.

**Comment by timholy** [comment]
Yeah, I see your point.

Also, I should add that the non-deterministic error you saw is one I've seen too. I haven't traced it down yet (and neither has anyone else, it seems), but You Are Not Alone.

**Comment by lucasb-eyer** [comment]
Let me know if

1. you'd like to keep the changes as-is and I need to add doc+test (and rename to remove `!`?), or
2. you'd rather not introduce `cumodules` as a global, ignoring the inconsistency. Then, I'll undo that part, keep the `ptxdict` cleanup fix and possibly add a test.

**Comment by timholy** [comment]
Let's do it. Sorry for the delay here.

**Comment by lucasb-eyer** [comment]
This is a side-thing of mine, so no hurry. I'll add doc+test soon then, shouldn't be much.

**Comment by lucasb-eyer** [comment]
I removed `!` from the names and added docs+test.

Note that I didn't export the names `init` and `close` as they are extremely general, my guess is we should direct users to use the fully-qualified `CUDArt.init` name.

I think now we could also merge the `ptxdict` and `mdutils` into a single dict to make code more robust to change. If you agree, I'll do that in a separate PR.

**Comment by timholy** [comment]
Thanks! Quite a lot prettier (internally and externally), I'm grateful.

**Comment by timholy** [comment]
> Note that I didn't export the names init and close as they are extremely general, my guess is we should direct users to use the fully-qualified CUDArt.init name.

Yes, good call.

> I think now we could also merge the ptxdict and mdutils into a single dict to make code more robust to change. If you agree, I'll do that in a separate PR.

I haven't looked carefully, but that seems reasonable.

**Pull request merged**
