### PR TITLE
RFC: split off CUDA driver interactions in separate package

### PR DESCRIPTION
**Pull request by maleadt**
This implements what I've mentioned a while back in https://github.com/JuliaGPU/CUDA.jl/pull/16#issuecomment-185654993: splitting off the CUDA driver interactions to a separate package, [CUDAdrv.jl](https://github.com/JuliaGPU/CUDAdrv.jl/tree/reorg), and making both CUDArt.jl and [CUDAnative.jl](https://github.com/JuliaGPU/CUDAnative.jl/tree/reorg) depend on it.

CUDAdrv.jl is not part of METADATA yet, so this is obviously not ready to merge, but other than that I feel pretty happy with how it turned out. It provides manually written (ie. not Clang.jl generated because of the versioning ickiness), and a `ccall`-like `cudacall` for calling kernels. This PR makes CUDArt use some of that functionality.

There's still other functionality to deduplicate, eg. the different pointers and array types, but I don't feel confident messing with that and it would probably be a breaking change.

I've also sneaked in some 0.5 compatibility changes for which I depend on Compat.

### CODE REVIEW

**Comment by timholy** [comment]
LGTM. Thanks for the deprecation fixes, too!

Merge whenever you're ready.

**Comment by maleadt** [comment]
CUDAdrv just got registered, so I'll be merging this.

**Comment by timholy** [comment]
Do the CUDArt tests pass for you? They don't for me. At a minimum I need this patch to CUDAdrv:
```diff

$ git diff execution.jl
diff --git a/src/execution.jl b/src/execution.jl
index 9320ab0..0e1692a 100644
--- a/src/execution.jl
+++ b/src/execution.jl
@@ -53,12 +53,12 @@ end
 ccall-like interface to launching a CUDA function on a GPU
 """
 function cudacall(f::CuFunction, griddim::CuDim, blockdim::CuDim, types, values...;
-                  shmem=0, stream::CuStream=default_stream())
+                  shmem=0, stream=default_stream())
     tt = Base.to_tuple_type(types)
 
     # convert the values to match the kernel's signature (specified by the user)
     values = map(pair -> Base.unsafe_convert(pair[1], Base.cconvert(pair[1],pair[2])),
                  zip(tt.parameters,values))
 
-    launch(f, CuDim3(griddim), CuDim3(blockdim), shmem, stream, values)
+    launch(f, CuDim3(griddim), CuDim3(blockdim), shmem, convert(CuStream, stream), values)
 end
```
but there are still problems with the test for `wait`. (That problem might be due to julia-0.5 changes, however.)

**Comment by maleadt** [comment]
All tests pass here (except for the `gc` ones which fail non-deterministically, but that's unrelated).
This seems to be caused by passing a `CUDArt.Stream` to `cudacall` in `cudasleep`, which is only tested in a multi-GPU test. I only have a single GPU in my dev system... :-)

I'll submit a PR.

**Pull request merged**
